### PR TITLE
Upgrade `@actions/cache` dependency and remove workaround

### PR DESCRIPTION
**Pull request by darkdragon-001**
The linked issue has been fixed upstream. Updating to the version containing the fix and removing the workaround.

### CODE REVIEW

**Comment by bbhtt** [comment]
Please run `yarn install` for `flat-manager` before running `ncc build ./flat-manager/index.js -o ./flat-manager/dist/`, it deleted most of the contents.

**Comment by darkdragon-001** [comment]
@bbhtt Oops, I restored the original file.

**Comment by darkdragon-001** [comment]
@barthalion @bbhtt could you please take a look? Thanks!

**Comment by bbhtt** [comment]
Seems fine. Workaround was added in https://github.com/flatpak/flatpak-github-actions/pull/149/

**Pull request merged**
